#!/bin/bash

. $ZDOTDIR/.shared_env # for ZDOT_FIND_HOOKS
. $ZDOTDIR/.zsh/functions/enable_nullglob

if [ "$1" == '-l' ]; then
    list=yes
    shift
fi

for profile in "$@"; do
    . $ZDOT_FIND_HOOKS ".mutt/${profile}.d"
done | sort-by-filename |
while read hook; do
    if [ -n "$list" ]; then
        echo "$hook"
    elif [ -x "$hook" ]; then
        cat <<EOF
#########################################################################
# Output of executable $hook follows:

EOF
        if ! "$hook"; then
            echo "# Hook failed with exit code $?"
            echo "Hook $hook failed with exit code $?" >&2
        fi
        echo
    else
        cat <<EOF
#########################################################################
# $hook follows:

EOF
        cat "$hook"
        echo
    fi
done

